Src/Controllers/PrivacyController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace AntiKernelBlog.Controllers
{
    public class PrivacyController : Controller
    {
        [Route("/privacy")]
        public async Task<IActionResult> Privacy()
        {
            return await Task.Run(() => View());
        }
    }
}

Src/Pages/Archive.cshtml
@page
@model ArchivePage<StandardArchive, Piranha.Models.PostInfo>
@{
    ViewData["Title"] = !string.IsNullOrEmpty(Model.Data.MetaTitle) ? Model.Data.MetaTitle : Model.Data.Title;
    var hasImage = Model.Data.PrimaryImage.HasValue;

    var posts = Model.Archive.Posts.Count;
}
@section head {
    @WebApp.MetaTags(Model.Data)
}

<header @(hasImage ? "class=has-image" : "") @(hasImage ? $"style=background-image:url({ @Url.Content(WebApp.Media.ResizeImage(Model.Data.PrimaryImage, 1920, 400)) })" : "")>
    <div class="dimmer"></div>
    <div class="container text-center">
        <h1>@Model.Data.Title</h1>
        @if (!string.IsNullOrWhiteSpace(Model.Data.Excerpt))
        {
            <div class="row justify-content-center">
                <div class="col-lg-8 lead">
                    @Html.Raw(Model.Data.Excerpt)
                </div>
            </div>
        }
    </div>
</header>

<main class="archive">
    @foreach (var block in Model.Data.Blocks)
    {
        <div class="block @block.CssName()">
            <div class="container">
                @Html.DisplayFor(m => block, block.GetType().Name)
            </div>
        </div>
    }
    <div class="container">
        @for (var n = 0; n < posts; n += 2)
        {
            <div class="row">
                @for (var i = n; i < Math.Min(posts, n + 2); i++)
                {
                    var post = Model.Archive.Posts[i];

                    <div class="@(i == 0 ? "col-md-12" : "col-md-6")">
                        <article>
                            <header>
                                @if (post.PrimaryImage.HasValue)
                                {
                                    <a href="@post.Permalink">
                                        <img class="rounded mb-3" src="@Url.Content(WebApp.Media.ResizeImage(post.PrimaryImage, 1140, 450))" alt="@post.PrimaryImage.Media.AltText">
                                    </a>
                                }
                                <h3>@post.Title</h3>
                                <p class="post-meta">
                                    <span>
                                        In <a href="@Model.Data.Permalink/category/@post.Category.Slug">@post.Category.Title</a>
                                    </span>
                                    <span>
                                        Tags
                                        @foreach (var tag in post.Tags)
                                        {
                                            <a href="@Model.Data.Permalink/tag/@tag.Slug">#@tag.Slug</a>
                                        }
                                    </span>
                                    @if (post.IsPublished)
                                    {
                                        <span>
                                            Published @post.Published.Value.ToShortDateString()
                                        </span>
                                    }
                                    @if (post.EnableComments && post.CommentCount > 0)
                                    {
                                        <span>
                                            <a href="@post.Permalink#comments">@post.CommentCount @(post.CommentCount == 1 ? "comment" : "comments")</a>
                                        </span>
                                    }
                                </p>
                                <p>@Html.Raw(post.Excerpt)</p>
                                <a href="@post.Permalink" class="btn btn-primary">Read more</a>
                            </header>
                        </article>
                    </div>
                    @if (i == 0)
                    {
                        n--;
                        break;
                    }
                }
            </div>
        }
    </div>
</main>

Src/Pages/Page.cshtml
@page
@model SinglePage<StandardPage>
@{
    ViewData["Title"] = !string.IsNullOrEmpty(Model.Data.MetaTitle) ? Model.Data.MetaTitle : Model.Data.Title;
    var hasImage = Model.Data.PrimaryImage.HasValue;
}
@section head {
    @WebApp.MetaTags(Model.Data)
}

<header @(hasImage ? "class=has-image" : "") @(hasImage ? $"style=background-image:url({ @Url.Content(WebApp.Media.ResizeImage(Model.Data.PrimaryImage, 1920, 400)) })" : "")>
    <div class="dimmer"></div>
    <div class="container text-center">
        <h1>@Model.Data.Title</h1>
        @if (!string.IsNullOrWhiteSpace(Model.Data.Excerpt))
        {
            <div class="row justify-content-center">
                <div class="col-lg-8 lead">
                    @Html.Raw(Model.Data.Excerpt)
                </div>
            </div>
        }
    </div>
</header>

<main>
    @foreach (var block in Model.Data.Blocks)
    {
        <div class="block @block.CssName()">
            <div class="container">
                @Html.DisplayFor(m => block, block.GetType().Name)
            </div>
        </div>
    }
</main>

Src/Pages/Post.cshtml
@page
@model SinglePostWithComments<StandardPost>
@{
    ViewData["Title"] = !string.IsNullOrEmpty(Model.Data.MetaTitle) ? Model.Data.MetaTitle : Model.Data.Title;
    var hasImage = Model.Data.PrimaryImage.HasValue;
    var archive = await WebApp.Api.Pages.GetByIdAsync(Model.Data.BlogId);
}
@section head {
    @WebApp.MetaTags(Model.Data)
}

<header @(hasImage ? "class=has-image" : "") @(hasImage ? $"style=background-image:url({ @Url.Content(WebApp.Media.ResizeImage(Model.Data.PrimaryImage, 1920, 400)) })" : "")>
    <div class="dimmer"></div>
    <div class="container text-center">
        <h1>@Model.Data.Title</h1>
        <p class="post-meta">
            <span>
                In <a href="@archive.Permalink/category/@Model.Data.Category.Slug">@Model.Data.Category.Title</a>
            </span>
            <span>
                Tags
                @foreach (var tag in Model.Data.Tags)
                {
                    <a href="@archive.Permalink/tag/@tag.Slug">#@tag.Slug</a>
                }
            </span>
            @if (Model.Data.IsPublished)
            {
                <span>
                    Published @Model.Data.Published.Value.ToShortDateString()
                </span>
            }
            @if (Model.Data.EnableComments && Model.Data.CommentCount > 0)
            {
                <span>
                    <a href="#comments">@Model.Data.CommentCount @(Model.Data.CommentCount == 1 ? "comment" : "comments")</a>
                </span>
            }
        </p>
        @if (!string.IsNullOrWhiteSpace(Model.Data.Excerpt))
        {
            <div class="row justify-content-center">
                <div class="col-lg-8 lead">
                    @Html.Raw(Model.Data.Excerpt)
                </div>
            </div>
        }
    </div>
</header>

<main>
    @foreach (var block in Model.Data.Blocks)
    {
        <div class="block @block.CssName()">
            <div class="container">
                @Html.DisplayFor(m => block, block.GetType().Name)
            </div>
        </div>
    }
    @if (Model.Data.EnableComments)
    {
        <div id="comments" class="container comments">
            @if (Model.Data.IsCommentsOpen)
            {
                <div class="alert alert-comment mt-2 mb-5">
                    <form asp-page-handler="SaveComment" method="post">
                        @Html.AntiForgeryToken()
                        @Html.Hidden("Id", Model.Data.Id)

                        <h3 class="mb-3">Leave a comment</h3>
                        <p class="mb-4">
                            Please note that we won't show your email to others, or use it for sending
                            unwanted emails. We will only use it to render your Gravatar image and to
                            validate you as a real person.
                        </p>
                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group">
                                    <input name="CommentAuthor" type="text" class="form-control" placeholder="Your name">
                                </div>
                            </div>
                            <div class="col-md-6">
                                <input name="CommentEmail" type="text" class="form-control" placeholder="Your email address">
                            </div>
                        </div>
                        <div class="form-group">
                            <input name="CommentUrl" type="text" class="form-control" placeholder="An (optional) URL to your website">
                        </div>
                        <div class="form-group">
                            <textarea name="CommentBody" rows="6" class="form-control" placeholder="Your awesome comment"></textarea>
                        </div>
                        <div class="form-group text-left">
                            <button class="btn btn-success">Post Comment</button>
                        </div>
                    </form>
                </div>
            }
            @Html.DisplayFor(m => m.Comments)
        </div>
    }
</main>

Src/Pages/_Layout.cshtml
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Lato:wght@300;400&family=Raleway:wght@700&display=swap">
    <link rel="stylesheet" href="~/assets/css/style.min.css" asp-append-version="true">

    @RenderSection("head", required: false)
</head>

<body>

    <!-- Top menu -->
    <nav class="navbar navbar-expand-md navbar-light fixed-top">
        <div class="container">
            <a class="navbar-brand" href="~/">Anti Kernel <small>Blog</small></a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarsExampleDefault">
                <ul class="navbar-nav ml-auto">
                    @foreach (var item in WebApp.Site.Sitemap.Where(i => !i.IsHidden))
                    {
        <li class="nav-item@(item.Id == WebApp.PageId || item.HasChild(WebApp.PageId) ? " active" : "")">
            <a class="nav-link" href="@WebApp.Url(item)">@item.MenuTitle</a>
        </li>}
                </ul>
            </div>
        </div>
    </nav>
    <!-- End top menu -->

    @RenderBody()

    <footer class="border-top footer text-muted padding-top padding-bottom">
        <div class="container">
            &copy; 2020 - Anti Kernel - <a asp-area="" asp-controller="Privacy" asp-action="Privacy">Política de Privacidade</a>
        </div>
    </footer>

    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</body>
</html>